# Use your specified image as the base
FROM jshark2010/apache-stig-fusion:t

# Copy the website files into the container
COPY app/index.html /usr/local/apache2/htdocs/
COPY img/logo.png /usr/local/apache2/htdocs/

# Expose port 80
EXPOSE 80
